### ISSUE TITLE
Subscriber.NonSubscription field unmarshals with error

### ISSUE THREAD

**Issue by FedoseevAlex** [iktakahiro/revcatgo#11]
Hello! 
It seems that there is a small difference between revenue cat API and Subscriber structure in revcatgo.
Subscriber struct looks like:
```go
type Subscriber struct {
	Entitlements      map[string]Entitlement     `json:"entitlements"`
	FirstSeen         time.Time                  `json:"first_seen"`
	LastSeen          time.Time                  `json:"last_seen"`
	ManagementURL     null.String                `json:"management_url"`
	OriginalAppUserID null.String                `json:"original_app_user_id"`
	Subscriptions     map[string]Subscription    `json:"subscriptions"`
	NonSubscription   map[string]NonSubscription `json:"non_subscriptions"` // <--- Here is the map of NonSubscription objects
}
```

And revenue cat api defines the Subscriber.NonSubscription as `map[string][]NonSubscription` ([proof](https://www.revenuecat.com/docs/api-v1#tag/customers/operation/subscribers)).
Because of that some of user purchases may be missing. 

I suggest changing the type of the field according to revenue cat api docs.

Thank you in advance!

**Comment by iktakahiro** [comment]
I've confirmed data structured, you are right! I'll merged your pull-request.

![CleanShot 0006-12-04 at 23 42 24@2x](https://github.com/user-attachments/assets/565d278e-48fc-41c5-9969-156fed357efe)

**Comment by jackhopner** [comment]
Hi @iktakahiro 

This structure only changed in the v2 API which is still under development, can we revert this?
